### ISSUE TITLE
BibTeX file should be included in the note instead of being set up in the options

### ISSUE THREAD

**Issue by extall** [joplin/plugin-bibtex#24]
The BibTeX file must be pulled from an attachment of the current note and not from the location specified in the plugin options (huge usability issue!). The references list should appear where the attachment is specified in MD. Handling multiple attachments is not required at this stage as it would be much more difficult to implement, it is enough to parse the first found .bib attachment.

Example workflow: add a .bib file to the note; open the attachment in JabRef and add references; since the file is watched the newly added references are pulled onto the note workspace, the author can then immediately insert them into the note.

**Comment by laurent22** [comment]
Why not create a BibTex file that contains all the references you might need?

**Comment by extall** [comment]
@laurent22 : .bib files are essentially databases. There will never be a single database that contains everything because there can be many different research projects that are not even related, and for each of these one needs to be able to have a distinct database containing relevant research references.

**Comment by xUser5000** [comment]
@extall 
I've just released a new version that includes support for importing multiple `.bib` files from the config screen. Is that what you mean?

**Comment by extall** [comment]
@xUser5000 : from Joplin's plugin management page, I can only see v0.4 at the moment, I guess it takes some time for the release to push through. I will wait for v0.5 to become available and will let you know.

By the way, I see that the changes were committed within the past hour, and if the plugin will support the above mentioned feature, then talk about good timing :)

**Comment by extall** [comment]
@xUser5000 : to speed up the process, I built the plugin from source.

I can see that in the options it is possible to import multiple BibTeX files, but that is not what I mean. What I mean is, you should just be able to attach a relevant `.bib` file to a given note to work with the references in that attachment.

I mean, think about it this way. Suppose I have 4 different computers and a central Joplin cloud database for synchronization. Do I have to, for each BibTeX file, locate it on disk on each computer? I mean options are not automatically synchronized and besides that the locations of those files can be different on each machine. It becomes especially frustrating when I have dozens of those BibTeX files each serving a specific purpose.

**Comment by extall** [comment]
@xUser5000 @laurent22 any follow-up thoughts on this, gentlemen? If it this feature request seems like it could lead to too much work or it does not align properly with your development plans or philosophy, I can also proceed with the development of this feature in a fork.

**Comment by xUser5000** [comment]
@extall Actually, I have my hands full right now with other features and bug fixes, so you are pretty much welcome to fork the repo and work on this feature.

**Comment by extall** [comment]
@xUser5000 : perfectly understandable. I will do that. Hence, closing this issue for now.

**Comment by extall** [comment]
@xUser5000 : perfectly understandable. I will do that. Hence, closing this issue for now.
